/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.woo.checklist;

import com.woo.checklist.dao.ToDoDao;
import com.woo.checklist.handler.toDo.ToDoAddHandler;
import com.woo.checklist.handler.toDo.ToDoDeleteHandler;
import com.woo.checklist.handler.toDo.ToDoListHandler;
import com.woo.checklist.handler.toDo.ToDoModifyHandler;
import com.woo.checklist.handler.toDo.ToDoViewHandler;
import com.woo.menu.MenuGroup;
import com.woo.util.Prompt;

public class ClientApp {

  Prompt prompt = new Prompt(System.in);

  ToDoDao toDoDao;

  MenuGroup mainMenu;

  ClientApp() {
//    prepareDatabase();
    prepareMenu();
  }

  public static void main(String[] args) {
    System.out.println("[To do list]");
    new ClientApp().run();
  }

  void prepareMenu() {
    mainMenu = MenuGroup.getInstance("메인");

    MenuGroup toDoMenu = mainMenu.addGroup("할 일들");
    toDoMenu.addItem("등록", new ToDoAddHandler(toDoDao, prompt));
    toDoMenu.addItem("조회", new ToDoViewHandler(toDoDao, prompt));
    toDoMenu.addItem("수정", new ToDoModifyHandler(toDoDao, prompt));
    toDoMenu.addItem("완료", new ToDoDeleteHandler(toDoDao, prompt));
    toDoMenu.addItem("목록", new ToDoListHandler(toDoDao, prompt));

  }

//  void prepareDatabase() {
//    try {
//      // JVM이 JDBC 드라이버 파일(.jar)에 설정된대로 자동으로 처리한다.
////      Driver driver = new com.mysql.cj.jdbc.Driver();
////      DriverManager.registerDriver(driver);
//
//      Connection con = DriverManager.getConnection(
////          "jdbc:mysql://localhost/checklist", "study", "Bitcamp!@#123");
//          "jdbc:mysql://db-ld285-kr.vpc-pub-cdb.ntruss.com/studydb", "study", "Bitcamp!@#123");
//
//      toDoDao = new ToDoDaoImpl(con);
//
//    } catch (Exception e) {
//      System.out.println("통신 오류!");
//      e.printStackTrace();
//    }
//  }

  void run() {
    while (true) {
      try {
        mainMenu.execute(prompt);
        prompt.close();
        break;
      } catch (Exception e) {
        System.out.println("예외 발생!");
      }
    }
  }
}
