/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.woo.checklist;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void appHasAGreeting() {
    ServerApp classUnderTest = new ServerApp();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
