/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.test;

import java.net.InetAddress;

public class Main {
  public static void main(String[] args) throws Exception {
    InetAddress local = InetAddress.getLocalHost();
    System.out.println(local.getHostAddress());
  }
}

