/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.woo.checklist;

import com.woo.util.Prompt;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;

public class ClientApp {

  Prompt prompt = new Prompt(System.in);
  String serverAddress;
  int port;


  public static void main(String[] args) {
    new ClientApp().
        setAddress("localhost").
        setPort(8888).
        run();
  }

  ClientApp setAddress(String serverAddress) {
    this.serverAddress = serverAddress;
    return this;
  }

  ClientApp setPort(int port) {
    this.port = port;
    return this;
  }

  void run() {
    try (Socket socket = new Socket(serverAddress, port);
        DataOutputStream out = new DataOutputStream(socket.getOutputStream());
        DataInputStream in = new DataInputStream(socket.getInputStream())
    ) {
      while (true) {
        String reply = in.readUTF();
        if (reply.equals("[[quit!]]")) {
          break;
        }
        System.out.print(reply);

        out.writeUTF(prompt.input(""));
      }

      System.out.println("클라이언트 종료!");

    } catch (Exception e) {
      System.out.println("서버 연결 오류!");
      e.printStackTrace();
    }
  }

}