/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.woo.checklist;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ClientApp classUnderTest = new ClientApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
